name: main

on:
  push:
    paths-ignore:
      - .github/**
    branches:
      - main
      
  workflow_dispatch: 
  
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    env:
      DATABRICKS_HOST: ${{ secrets.DEV_DEPLOYMENT_TARGET_URL }}
      DATABRICKS_TOKEN: ${{ secrets.DEV_DEPLOYMENT_TARGET_TOKEN }}
      REPO_PATH: /Workspace/Users/vasu_nalam@yahoo.com/CICD-DATABRICKS-PROJECT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: SET UP DATABRICKS CLI
        uses: databricks/setup-cli@main

      # - name: Extract branch name
      #   id: extract_branch
      #   run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      
      # - name: Update Databricks Repo (Dev)
      #   run:
      #     databricks repos update "${{ env.REPO_PATH }}" \
      #     --branch "${{ steps.extract_branch.outputs.branch }}"

      - name: Get Databricks Repo ID
        id: get_repo
        run: |
          repo_id=$(databricks repos list --output json | \
            jq -r '.[] | select(.path=="'"${REPO_PATH}"'") | .id')
      
          if [ -z "$repo_id" ]; then
            echo "Repo not found!"
            exit 1
          fi
      
          echo "repo_id=$repo_id" >> $GITHUB_OUTPUT
      
      - name: Update Databricks Repo (Dev)
        run: |
          databricks repos update "${{ steps.get_repo.outputs.repo_id }}" \
            --branch "${{ github.ref_name }}"

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: production
    env:
      DATABRICKS_HOST: ${{ secrets.PRD_DEPLOYMENT_TARGET_URL }}
      DATABRICKS_TOKEN: ${{ secrets.PRD_DEPLOYMENT_TARGET_TOKEN }}
      REPO_PATH: /Workspace/Users/vasu_nalam@yahoo.com/PRD-CICD-DATABRICKS-PROJECT

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: SET UP DATABRICKS CLI
        uses: databricks/setup-cli@main

      # - name: Extract branch name
      #   id: extract_branch
      #   run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

      # - name: Update Databricks Repo (Prod)
      #   run:
      #     databricks repos update "${{ env.REPO_PATH }}" \
      #     --branch "${{ steps.extract_branch.outputs.branch }}"


      - name: Get Databricks Repo ID
        id: get_repo
        run: |
          repo_id=$(databricks repos list --output json | \
            jq -r '.[] | select(.path=="'"${REPO_PATH}"'") | .id')
      
          if [ -z "$repo_id" ]; then
            echo "Repo not found!"
            exit 1
          fi
      
          echo "repo_id=$repo_id" >> $GITHUB_OUTPUT
      
      - name: Update Databricks Repo (Prod)
        run: |
          databricks repos update "${{ steps.get_repo.outputs.repo_id }}" \
            --branch "${{ github.ref_name }}"
        
